const nabesCrosswalk = {
  101: [
    'Battery Park City',
    'Civic Center',
    'Ellis Island',
    'Governors Island',
    'Liberty Island',
    'South Street Seaport',
    'Tribeca',
    'Wall Street',
    'World Trade Center',
  ],
  102: [
    'Greenwich Village',
    'Hudson Square',
    'Little Italy',
    'NoHo',
    'SoHo',
    'South Village',
    'West Village',
  ],
  103: [
    'Chinatown',
    'East Village',
    'Lower East Side',
    'NoHo',
    'Two Bridges',
  ],
  104: [
    'Chelsea',
    'Clinton',
    'Hudson Yards',
  ],
  105: [
    'Flatiron',
    'Gramercy Park',
    'Herald Square',
    'Midtown',
    'Midtown South',
    'Murray Hill',
    'Times Square',
    'Union Square',
  ],
  106: [
    'Beekman Place',
    'Gramercy Park',
    'Murray Hill',
    'Peter Cooper Village',
    'Stuyvesant Town',
    'Sutton Place',
    'Tudor City',
    'Turtle Bay',
  ],
  107: [
    'Lincoln Square',
    'Manhattan Valley',
    'Upper West Side',
  ],
  108: [
    'Carnegie Hill',
    'Lenox Hill',
    'Roosevelt Island',
    'Upper East Side',
    'Yorkville',
  ],
  109: [
    'Hamilton Heights',
    'Manhattanville',
    'Morningside Heights',
    'West Harlem',
  ],
  110: [
    'Central Harlem',
  ],
  111: [
    'East Harlem',
    'Harlem',
    'Randall&apos;s Island Park',
    'Wards Island Park',
  ],
  112: [
    'Inwood',
    ' Washington Heights',
  ],
  201: [
    'Melrose',
    'Mott Haven',
    'Port Morris',
  ],
  202: [
    'Hunts Point',
    'Longwood',
  ],
  203: [
    'Claremont',
    'Crotona Park East',
    'Melrose',
    'Morrisania',
  ],
  204: [
    'Concourse',
    'Concourse Village',
    'East Concourse',
    'Highbridge',
    'Mount Eden',
  ],
  205: [
    'Fordham',
    'Morris Heights',
    'Mount Hope',
    'University Heights',
  ],
  206: [
    'Bathgate',
    'Belmont',
    'Bronx Park South',
    'East Tremont',
    'West Farms',
  ],
  207: [
    'Bedford Park',
    'Fordham',
    'Kingsbridge Heights',
    'Norwood',
    'University Heights',
  ],
  208: [
    'Fieldston',
    'Kingsbridge',
    'Marble Hill (MN)',
    'North Riverdale',
    'Riverdale',
    'Spuyten Duyvil',
  ],
  209: [
    'Bronx River',
    'Castle Hill',
    'Clason Point',
    'Harding Park',
    'Parkchester',
    'Soundview',
    'Soundview-Bruckner',
    'Unionport',
  ],
  210: [
    'City Island',
    'Co-op City',
    'Country Club',
    'Edgewater Park',
    'Pelham Bay',
    'Schuylerville',
    'Throgs Neck',
    'Westchester Square',
  ],
  211: [
    'Allerton',
    'Bronxdale',
    'Indian Village',
    'Morris Park',
    'Pelham Gardens',
    'Pelham Parkway',
    'Van Nest',
  ],
  212: [
    'Baychester',
    'Eastchester',
    'Edenwald',
    'Olinville',
    'Wakefield',
    'Williamsbridge',
    'Woodlawn',
  ],
  301: [
    'East Williamsburg',
    'Greenpoint',
    'Northside',
    'Southside',
    'Williamsburg',
  ],
  302: [
    'Boerum Hill',
    'Brooklyn Heights',
    'Clinton Hill',
    'Downtown Brooklyn',
    'DUMBO',
    'Fort Greene',
    'Fulton Ferry',
    'Navy Yard',
    'Vinegar Hill',
  ],
  303: [
    'Bedford-Stuyvesant',
    'Stuyvesant Heights',
    'Tompkins Park North',
  ],
  304: [
    'Bushwick',
  ],
  305: [
    'Broadway Junction',
    'City Line',
    'Cypress Hills',
    'East New York',
    'Highland Park',
    'New Lots',
    'Spring Creek',
    'Starrett City',
  ],
  306: [
    'Carroll Gardens',
    'Cobble Hill',
    'Columbia St',
    'Gowanus',
    'Park Slope',
    'Red Hook',
  ],
  307: [
    'Sunset Park',
    'Windsor Terrace',
  ],
  308: [
    'Crown Heights',
    'Prospect Heights',
    'Weeksville',
  ],
  309: [
    'Crown Heights South',
    'Prospect Lefferts Gardens',
    'Wingate',
  ],
  310: [
    'Bay Ridge',
    'Dyker Heights',
    'Fort Hamilton',
  ],
  311: [
    'Bath Beach',
    'Bensonhurst',
    'Gravesend',
    'Mapleton',
  ],
  312: [
    'Borough Park',
    'Kensington',
    'Ocean Parkway',
  ],
  313: [
    'Brighton Beach',
    'Coney Island',
    'Gravesend',
    'Homecrest',
    'Sea Gate',
    'West Brighton',
  ],
  314: [
    'Ditmas Park',
    'Flatbush',
    'Manhattan Terrace',
    'Midwood',
    'Ocean Parkway',
    'Prospect Park South',
  ],
  315: [
    'Gerritsen Beach',
    'Gravesend',
    'Homecrest',
    'Kings Highway',
    'Manhattan Beach',
    'Plumb Beach',
    'Sheepshead Bay',
  ],
  316: [
    'Broadway Junction',
    'Brownsville',
    'Ocean Hill',
  ],
  317: [
    'East Flatbush',
    'Farragut',
    'Flatbush',
    'Northeast Flatbush',
    'Remsen Village',
    'Rugby',
    'Erasmus',
  ],
  318: [
    'Bergen Beach',
    'Canarsie',
    'Flatlands',
    'Georgetown',
    'Marine Park',
    'Mill Basin',
    'Mill Island',
    'Paerdegat Basin',
  ],
  401: [
    'Astoria',
    'Astoria Heights',
    'Queensbridge',
    'Dutch Kills',
    'Long Island City*',
    'Ravenswood',
    'Rikers Island (BX)',
    'Steinway',
  ],
  402: [
    'Blissville',
    'Hunters Point',
    'Long Island City',
    'Sunnyside',
    'Sunnyside Gardens',
    'Woodside',
  ],
  403: [
    'East Elmhurst',
    'Jackson Heights',
    'North Corona',
  ],
  404: [
    'Corona',
    'Corona Heights',
    'Elmhurst',
    'Lefrak City',
  ],
  405: [
    'Glendale',
    'Maspeth',
    'Middle Village',
    'Ridgewood',
  ],
  406: [
    'Forest Hills',
    'Forest Hills Gardens',
    'Rego Park',
  ],
  407: [
    'Auburndale',
    'Bay Terrace',
    'Beechhurst',
    'Clearview',
    'College Point',
    'Downtown Flushing',
    'East Flushing',
    'Flushing',
    'Malba',
    'Murray Hill',
    'Queensboro Hill',
    'Waldheim',
    'Whitestone',
  ],
  408: [
    'Briarwood',
    'Fresh Meadows',
    'Hillcrest',
    'Holliswood',
    'Jamaica',
    'Jamaica Estates',
    'Jamaica Hills',
    'Kew Gardens Hills',
    'Pomonok',
    'Utopia',
  ],
  409: [
    'Kew Gardens',
    'Ozone Park',
    'Richmond Hill',
    'Woodhaven',
  ],
  410: [
    'Howard Beach',
    'Lindenwood',
    'Old Howard Beach',
    'Ozone Park*',
    'South Ozone Park',
  ],
  411: [
    'Auburndale',
    'Bayside',
    'Douglaston',
    'Hollis Hills',
    'Little Neck',
    'Oakland Gardens',
  ],
  412: [
    'Hollis',
    'Jamaica',
    'Jamaica Center',
    'North Springfield Gardens',
    'Rochdale',
    'South Jamaica',
    'St. Albans',
  ],
  413: [
    'Bellaire',
    'Bellerose',
    'Brookville',
    'Cambria Heights',
    'Floral Park',
    'Glen Oaks',
    'Laurelton',
    'New Hyde Park',
    'Queens Village',
    'Rosedale',
    'Springfield Gardens',
  ],
  414: [
    'Arverne',
    'Bayswater',
    'Belle Harbor',
    'Breezy Point',
    'Broad Channel',
    'Edgemere',
    'Far Rockaway',
    'Hammels',
    'Neponsit',
    'Rockaway Park',
    'The Rockaways',
    'Roxbury',
    'Seaside',
    'Somerville',
  ],
  501: [
    'Arlington',
    'Castleton Corners',
    'Clifton',
    'Elm Park',
    'Fox Hills',
    'Graniteville',
    'Grymes Hill',
    'Howland Hook',
    'Livingston',
    'Mariner&apos;s Harbor',
    'New Brighton',
    'Old Place',
    'Park Hill',
    'Port Ivory',
    'Port Richmond',
    'Randall Manor',
    'Rosebank',
    'Shore Acres',
    'Silver Lake',
    'St. George',
    'Stapleton',
    'Sunnyside',
    'Tompkinsville',
    'Ward Hill',
    'West Brighton',
    'West New Brighton',
    'Westerleigh',
    'Willowbrook',
  ],
  502: [
    'Arrochar',
    'Bloomfield',
    'Bulls Head',
    'Chelsea',
    'Concord',
    'Dongan Hills',
    'Egbertville',
    'Emerson Hill',
    'Grant City',
    'Grasmere',
    'Heartland Village',
    'Lighthouse Hill',
    'Manor Heights',
    'Midland Beach',
    'New Dorp',
    'New Dorp Beach',
    'New Springville',
    'Old Town',
    'South Beach',
    'Todt Hill',
    'Travis',
    'Willowbrook',
  ],
  503: [
    'Annadale',
    'Arden Heights',
    'Bay Terrace',
    'Butler Manor',
    'Charleston',
    'Eltingville',
    'Fresh Kills',
    'Great Kills',
    'Greenridge',
    'Huguenot',
    'Oakwood',
    'Oakwood Beach',
    'Oakwood Heights',
    'Pleasant Plains',
    'Prince&apos;s Bay',
    'Richmond Town',
    'Richmond Valley',
    'Rossville',
    'Sandy Ground',
    'Tottenville',
    'Woodrow',
  ],
};

export default nabesCrosswalk;
