const nabesCrosswalk = {
  101: [
    'Battery Park City',
    'Civic Center',
    'Ellis Island',
    'Governors Island',
    'Liberty Island',
    'South Street Seaport',
    'Tribeca',
    'Wall Street',
    'World Trade Center',
  ],
  102: [
    'Greenwich Village',
    'Hudson Square',
    'Little Italy',
    'NoHo',
    'SoHo',
    'South Village',
    'West Village',
  ],
  103: [
    'Chinatown',
    'East Village',
    'Lower East Side',
    'NoHo',
    'Two Bridges',
  ],
  104: [
    'Chelsea',
    'Clinton',
    'Hudson Yards',
  ],
  105: [
    'Flatiron',
    'Gramercy Park',
    'Herald Square',
    'Midtown',
    'Midtown South',
    'Murray Hill',
    'Times Square',
    'Union Square',
  ],
  106: [
    'Beekman Place',
    'Gramercy Park',
    'Murray Hill',
    'Peter Cooper Village',
    'Stuyvesant Town',
    'Sutton Place',
    'Tudor City',
    'Turtle Bay',
  ],
  107: [
    'Lincoln Square',
    'Manhattan Valley',
    'Upper West Side',
  ],
  108: [
    'Carnegie Hill',
    'Lenox Hill',
    'Roosevelt Island',
    'Upper East Side',
    'Yorkville',
  ],
  109: [
    'Hamilton Heights',
    'Manhattanville',
    'Morningside Heights',
    'West Harlem',
  ],
  110: [
    'Central Harlem',
  ],
  111: [
    'East Harlem',
    'Harlem',
    'Randall&apos;s Island Park',
    'Wards Island Park',
  ],
  112: [
    'Inwood',
    ' Washington Heights',
  ],
  201: [
    'Melrose',
    'Mott Haven',
    'Port Morris',
  ],
  202: [
    'Hunts Point',
    'Longwood',
  ],
  203: [
    'Claremont',
    'Crotona Park East',
    'Melrose',
    'Morrisania',
  ],
  204: [
    'Concourse',
    'Concourse Village',
    'East Concourse',
    'Highbridge',
    'Mount Eden',
  ],
  205: [
    'Fordham',
    'Morris Heights',
    'Mount Hope',
    'University Heights',
  ],
  206: [
    'Bathgate',
    'Belmont',
    'Bronx Park South',
    'East Tremont',
    'West Farms',
  ],
  207: [
    'Bedford Park',
    'Fordham',
    'Kingsbridge Heights',
    'Norwood',
    'University Heights',
  ],
  208: [
    'Fieldston',
    'Kingsbridge',
    'Marble Hill (MN)',
    'North Riverdale',
    'Riverdale',
    'Spuyten Duyvil',
  ],
  209: [
    'Bronx River',
    'Castle Hill',
    'Clason Point',
    'Harding Park',
    'Parkchester',
    'Soundview',
    'Soundview-Bruckner',
    'Unionport',
  ],
  210: [
    'City Island',
    'Co-op City',
    'Country Club',
    'Edgewater Park',
    'Pelham Bay',
    'Schuylerville',
    'Throgs Neck',
    'Westchester Square',
  ],
  211: [
    'Allerton',
    'Bronxdale',
    'Indian Village',
    'Morris Park',
    'Pelham Gardens',
    'Pelham Parkway',
    'Van Nest',
  ],
  212: [
    'Baychester',
    'Eastchester',
    'Edenwald',
    'Olinville',
    'Wakefield',
    'Williamsbridge',
    'Woodlawn',
  ],
  301: [
    'East Williamsburg',
    'Greenpoint',
    'Northside',
    'Southside',
    'Williamsburg',
  ],
  302: [
    'Boerum Hill',
    'Brooklyn Heights',
    'Clinton Hill',
    'Downtown Brooklyn',
    'DUMBO',
    'Fort Greene',
    'Fulton Ferry',
    'Navy Yard',
    'Vinegar Hill',
  ],
  303: [
    'Bedford-Stuyvesant',
    'Stuyvesant Heights',
    'Tompkins Park North',
  ],
  304: [
    'Bushwick',
  ],
  305: [
    'Broadway Junction',
    'City Line',
    'Cypress Hills',
    'East New York',
    'Highland Park',
    'New Lots',
    'Spring Creek',
    'Starrett City',
  ],
  306: [
    'Carroll Gardens',
    'Cobble Hill',
    'Columbia St',
    'Gowanus',
    'Park Slope',
    'Red Hook',
  ],
  307: [
    'Sunset Park',
    'Windsor Terrace',
  ],
  XXX: [

  ],
};

export default nabesCrosswalk;
